### ISSUE TITLE
Permissions

### ISSUE THREAD

**Issue by xhoy** [reneeb/otrs-FlexibleTicketModule#1]
Then some directory's are missing: 
Message: FlexibleTicketModule-4.0.1: No such file: /usr/share/otrs/Custom/Kernel/Modules/AgentFlexibleTicketDialog.pm!
etc etc. Could they createded manually?

and maby by default they do not have the correct permissions? or atleaast /custom doesnt have them?

**Comment by xhoy** [comment]
Oke, it auto creates the directoy's but doesn have permissions

**Comment by reneeb** [comment]
How do you install the addon? Via webinterface or on commandline? Did you run otrs.SetPermissions.pl? Usually the Custom/ directory should have the correct permissions, but when you install addons as the otrs user or root via commandline and Apache doesn't run as that user you have to re-run otrs.SetPermissions.pl.

**Comment by xhoy** [comment]
Well, i refurbished old install. will test for new install tomorrow. there were some leftover's in Custom/ so maybe.... :) But it seems to be working atm! ill get back to you tomorrow.

**Comment by xhoy** [comment]
Tried it on a fresh install and it worked so ther eis no permission issue!
