### ISSUE TITLE
otrs 5 versio typo?

### ISSUE THREAD

**Issue by xhoy** [reneeb/otrs-FlexibleTicketModule#4]
`Backend ERROR: OTRS-CGI-1 Perl: 5.18.2 OS: linux Time: Wed Nov 4 21:14:55 2015 Message: Module Kernel/Output/HTML/TicketMenuFlexibleModule.pm not in @INC (/opt/otrs/Custom /opt/otrs/Kernel/cpan-lib /opt/otrs/ /etc/perl /usr/local/lib/perl/5.18.2 /usr/local/share/perl/5.18.2 /usr/lib/perl5 /usr/share/perl5 /usr/lib/perl/5.18 /usr/share/perl/5.18 /usr/local/lib/site_perl . /etc/apache2) RemoteAddress:123.123.123.123 RequestURI: /otrs/index.pl?Action=AgentTicketZoom;TicketID=177832 Traceback (1312): Module: Kernel::Modules::AgentTicketZoom::MaskAgentZoom Line: 986 Module: Kernel::Modules::AgentTicketZoom::Run Line: 635 Module: Kernel::System::Web::InterfaceAgent::Run Line: 1036 Module: ModPerl::ROOT::ModPerl::Registry::opt_otrs_bin_cgi_2dbin_index_2epl::handler Line: 40 Module: (eval) (v1.99) Line: 206 Module: ModPerl::RegistryCooker::run (v1.99) Line: 206 Module: ModPerl::RegistryCooker::default_handler (v1.99) Line: 172 Module: ModPerl::Registry::handler (v1.99) Line: 31``

I think this is a typo, but i can't find it.TicketMenuFlexibleModule.pm is in TicketMenuFlexibleModule.pm

**Comment by xhoy** [comment]
I moved the file but that generated other issues that i could not 'solve' easy

**Comment by reneeb** [comment]
Did you change the SysConfig option Ticket::Frontend::MenuModule###212-FlexibleTicketDialog? If so, please reset it...

**Comment by xhoy** [comment]
Currently working fine!
